networks:
  local:
    external: false

services:
  jobdb:
    build: .
    environment:
      SECRET_KEY: insecure_example_change_me
    depends_on:
    - db
    networks:
    - local
    ports:
    - 8888:8888
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
    - POSTGRES_USER=jobdb
    - POSTGRES_PASSWORD=jobdb
    - POSTGRES_DB=jobdb
    networks:
    - local
    restart: unless-stopped
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:
