#!/bin/sh

set -ex

export DJANGO_SETTINGS_MODULE="jobdb.settings.production"

django-admin migrate

# shellcheck disable=SC2086
exec django-admin runserver --insecure 0.0.0.0:8888 >/proc/1/fd/1 2>/proc/1/fd/2
