# Generated by Django 5.0.6 on 2024-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applied",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Applied"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("user", "posting"),
                name="single_application_per_user_posting",
            ),
        ),
    ]
