# Generated by Django 5.0.6 on 2024-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="careers_url",
            field=models.URLField(
                default=None,
                help_text="Careers page URL",
                max_length=2048,
                unique=True,
                verbose_name="Careers URL",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="employees_est",
            field=models.CharField(
                default=None,
                max_length=100,
                verbose_name="Estimated number of employees",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="employees_est_source",
            field=models.CharField(
                default=None,
                max_length=500,
                verbose_name="Estimated number of employees source",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="hq",
            field=models.CharField(
                default=None,
                help_text="Company headquarters location",
                max_length=250,
                verbose_name="Headquarters",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default=None,
                max_length=500,
                unique=True,
                verbose_name="Company name",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(
                default=None,
                help_text="Company web site URL",
                max_length=2048,
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
