# Generated by Django 5.0.6 on 2024-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_company_careers_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="location",
            field=models.CharField(
                default=None, max_length=500, verbose_name="Role Location"
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="title",
            field=models.CharField(
                default=None, max_length=500, verbose_name="Role Title"
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="url",
            field=models.URLField(
                default=None,
                help_text="Job posting URL",
                max_length=2048,
                unique=True,
                verbose_name="Posting URL",
            ),
        ),
    ]
