# Generated by Django 5.0.6 on 2024-06-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_application_single_application_per_user_posting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applied",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Applied"
            ),
        ),
    ]
