# Generated by Django 5.0.6 on 2024-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(
                blank=True, max_length=2048, verbose_name="LinkedIn Profile"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Phone number"
            ),
        ),
    ]
