# Generated by Django 5.0.6 on 2024-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_posting_location_alter_posting_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="priority",
            field=models.IntegerField(
                choices=[(100, "High"), (200, "Normal"), (300, "Low")],
                default=200,
                verbose_name="Priority",
            ),
        ),
    ]
