# Generated by Django 5.0.6 on 2024-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_posting_location_alter_posting_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="priority",
            field=models.IntegerField(
                choices=[(1000, "High"), (500, "Normal"), (100, "Low")],
                default=500,
                verbose_name="Priority",
            ),
        ),
    ]
