# Generated by Django 5.0.6 on 2024-06-25 05:20

import jobdb.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_user_linkedin_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="careers_urls",
            field=jobdb.main.fields.URLArray(
                blank=True,
                help_text="Additional careers page URLs",
                null=True,
                verbose_name="Additional Careers URLs",
            ),
        ),
        migrations.AddField(
            model_name="posting",
            name="job_board_urls",
            field=jobdb.main.fields.URLArray(
                blank=True,
                help_text="Additional posting URLs that link to the main posting URL",
                null=True,
                verbose_name="Job Board URLs",
            ),
        ),
    ]
