# Generated by Django 5.0.6 on 2024-07-07 16:27

from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations import AddField, AlterField
from django.db.migrations import Migration as BaseMigration
from django.db.migrations import RunPython
from django.db.migrations.state import StateApps
from django.db.models import BooleanField, Case, F, When
from django.db.models.expressions import Value
from django.db.models.functions import Lower


def set_in_wa(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Posting = apps.get_model("main", "Posting")  # noqa
    Posting.objects.all().annotate(cmp_loc=Lower(F("location"))).update(
        in_wa=Case(
            When(cmp_loc__startswith="remote", then=Value(False)), default=True
        )
    )


class Migration(BaseMigration):
    dependencies = [
        ("main", "0004_company_priority"),
    ]

    operations = [
        AddField(
            model_name="posting",
            name="in_wa",
            field=BooleanField(
                null=True,
                verbose_name="In WA",
                help_text="Whether role is located in WA",
            ),
        ),
        RunPython(set_in_wa, RunPython.noop),
        AlterField(
            model_name="posting",
            name="in_wa",
            field=BooleanField(
                verbose_name="In WA", help_text="Whether role is located in WA"
            ),
        ),
    ]
