# Generated by Django 5.0.6 on 2024-06-25 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_company_careers_urls_posting_job_board_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.posting"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.company"
            ),
        ),
    ]
