# Generated by Django 5.0.6 on 2024-07-22 00:06

import re
from contextlib import suppress

from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations import AddField, AlterField
from django.db.migrations import Migration as BaseMigration
from django.db.migrations import RunPython
from django.db.migrations.state import StateApps
from django.db.models import CharField, IntegerField


def set_employees_est_num(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Company = apps.get_model("main", "Company")  # noqa
    companies = []
    for company in Company.objects.filter(employees_est_num=None):
        companies.append(company)
        with suppress(ValueError):
            company.employees_est_num = int(company.employees_est)
            continue
        if company.employees_est.strip() == "11-50":
            range_base = "15"
        else:
            range_base = company.employees_est.split("-", 1)[0].strip()
        company.employees_est_num = int(
            re.sub("[^0-9]", "", re.sub("[kK]", "000", range_base))
        )
    Company.objects.bulk_update(companies, ["employees_est_num"])


class Migration(BaseMigration):
    dependencies = [
        ("main", "0005_posting_in_wa"),
    ]

    operations = [
        AddField(
            model_name="company",
            name="employees_est_num",
            field=IntegerField(
                default=None,
                null=True,
                blank=True,
                verbose_name="Estimated number of employees",
            ),
        ),
        RunPython(set_employees_est_num, RunPython.noop),
        AlterField(
            model_name="company",
            name="employees_est",
            field=CharField(
                default=None,
                max_length=100,
                verbose_name="Estimated number or range of employees",
            ),
        ),
    ]
