# Generated by Django 5.0.6 on 2024-06-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0006_alter_application_posting_alter_application_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="comment",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Comment"
            ),
        ),
    ]
