# Generated by Django 5.0.6 on 2024-06-25 07:48

import jobdb.main.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_apikey_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applied",
            field=jobdb.main.fields.AppliedDateField(
                blank=True, verbose_name="Date Applied"
            ),
        ),
    ]
